#!/bin/bash
#
# This shell script collects the paths to all of the UFO fonts found under the directory
# tree provided, and then runs the UFO Normalizer on each of the UFOs.
#
# To run it, type the command `normalizeAll` followed by the path to the directory tree
# that contains the UFO fonts that you want to normalize.
#	normalizeAll <path_to_directory_tree>
#
# This script depends on the UFO Normalizer to be installed. To get it, open a Terminal
# window and run the following command:
#	git clone https://github.com/unified-font-object/ufoNormalizer
# Then install it by running the following two commands:
#	cd ufoNormalizer
#	sudo python setup.py develop
#
# To confirm that the UFO Normalizer is correctly installed, open a **new** Terminal
# window and run the folowing command:
#	ufonormalizer -h
# The tool is correctly installed if you get the usage information instead of a message
# that ends with the sentence "No such file or directory".
#
# It's recommended that you keep the UFO Normalizer always up to date. To do so, open a
# Terminal window and run the following two commands:
#	cd ufoNormalizer
#	git pull
#
# ----------------------------------------------------------------------------------------
#
# If you want to run `normalizeAll` from anywhere in your hard drive, you'll need to do
# **one** of these two things:
#
# A. create an alias in your shell's configuration file (e.g. .bash_profile), by adding
#    by adding this line to it:
#		alias normalizeAll='<full_path_to_normalizeAll_file>'
#
# B. create a symlink using this command:
#		ln -s <full_path_to_normalizeAll_file> normalizeAll
#    A file named "normalizeAll" will be created. Now place this file inside a folder
#    that is listed in the shell's $PATH variable. To get the list of folders, open a
#    Terminal window and run this command:
#		IFS=:; printf "%s\n" $PATH
#
# ----------------------------------------------------------------------------------------

ufonormalizerTool='ufonormalizer'


# Check if the UFO Normalizer tool is installed
if ! command -v "$ufonormalizerTool" >/dev/null; then
	echo "ERROR: ufonormalizer tool is not installed."
	echo "       Get it at https://github.com/unified-font-object/ufoNormalizer"
	exit 1
fi


# Test if input argument is a directory
if [[ -d "$1" ]]; then
	dirPath=$1
	cd "$dirPath"
	dirPath=`pwd`
	echo "Top directory: $dirPath"
elif [[ "$1" == "" ]]; then
	echo "No directory provided."
	exit 1
else
	echo "$1 is not a valid directory path."
	exit 1
fi

# Set newline as the Internal Field Separator.
# This way the paths are not split at space characters.
IFS=$'\n'

# Get the paths to all of the UFOs in the directory tree
ufoList=`find . -type d -name '*.ufo' | sed 's:^\./::'` # sed removes the trailing './'

if [[ -n "$ufoList" ]]; then
	ufoArray=($ufoList)
	echo "Found ${#ufoArray[@]} UFOs"
else
	echo "No UFOs where found."
fi

# Normalize each UFO
for path in $ufoList
do
	ufoPath="$dirPath/$path"
# 	echo $ufoPath
	$ufonormalizerTool "$ufoPath"
done
